### ISSUE TITLE
assetGroupIdExists check hard coded to ASoC NA DC

### ISSUE THREAD

**Issue by hurds** [jrocia/Integration-ASoC-and-Gitlab#2]
main/scripts/appscanasoc_create_application_asoc.sh includes line:

assetGroupIdExist=$(curl -k -s -X 'GET' 'https://cloud.appscan.com/api/v4/AssetGroups' 

hardcoding the check to the ASoC North American Data Center.

Possilbe update/fix?:
assetGroupIdExist=$(curl -k -s -X 'GET' 'https://$serviceUrl/api/v4/AssetGroups'

**Comment by jrocia** [comment]
Good catch... fixed.

**Comment by jrocia** [comment]
fixed
